from fastapi import APIRouter, HTTPException, Depends, status, Path
from typing import List
from bson import ObjectId
from pymongo import ReturnDocument

from ..models.meeting import MeetingCreate, MeetingInDB # Import Meeting models
from ..db.mongodb import get_database
from motor.motor_asyncio import AsyncIOMotorDatabase
from ..utils.dependencies import validate_object_id_sync

router = APIRouter()

async def get_meeting_collection(db: AsyncIOMotorDatabase = Depends(get_database)):
    """Dependency to get the 'meetings' collection."""
    return db.get_collection("meetings")

@router.post("/", response_model=MeetingInDB, status_code=status.HTTP_201_CREATED, response_model_by_alias=False)
async def create_meeting(
    meeting: MeetingCreate,
    collection = Depends(get_meeting_collection)
):
    """Creates a new meeting, automatically generating the mid."""
    try:
        # Use mode="json" for HttpUrl and handle datetime serialization if needed
        meeting_dict = meeting.model_dump()
        # Generate a new ObjectId for the mid field
        generated_mid = ObjectId()
        # Add the generated mid to the dictionary to be saved
        meeting_dict['mid'] = generated_mid

        # Insert the complete dictionary (including generated mid)
        insert_result = await collection.insert_one(meeting_dict)
        # Fetch the created document using the _id generated by MongoDB
        created_meeting = await collection.find_one({"_id": insert_result.inserted_id})
        if created_meeting:
            return MeetingInDB(**created_meeting)
        raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail="Meeting could not be created")
    except Exception as e:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail=f"Error creating meeting: {e}")

@router.get("/", response_model=List[MeetingInDB], response_model_by_alias=False)
async def read_meetings(
    skip: int = 0,
    limit: int = 100,
    collection = Depends(get_meeting_collection)
):
    """Retrieves a list of meetings with pagination."""
    meetings_cursor = collection.find().skip(skip).limit(limit)
    meetings = await meetings_cursor.to_list(length=limit)
    return [MeetingInDB(**meeting) for meeting in meetings]

@router.get("/{meeting_id}", response_model=MeetingInDB, response_model_by_alias=False)
async def read_meeting(
    meeting_id: str = Path(..., description="The BSON ObjectId of the meeting (meeting_id) as a string"),
    collection = Depends(get_meeting_collection)
):
    """Retrieves a specific meeting by ID."""
    validated_meeting_oid = validate_object_id_sync(meeting_id)
    meeting = await collection.find_one({"_id": validated_meeting_oid})
    if meeting:
        return MeetingInDB(**meeting)
    raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail=f"Meeting with id {meeting_id} not found")

@router.put("/{meeting_id}", response_model=MeetingInDB, response_model_by_alias=False)
async def update_meeting(
    meeting_update: MeetingCreate,
    meeting_id: str = Path(..., description="The BSON ObjectId of the meeting (meeting_id) as a string"),
    collection = Depends(get_meeting_collection)
):
    """Updates an existing meeting. Note: This setup won't update the mid."""
    validated_meeting_oid = validate_object_id_sync(meeting_id)
    meeting_dict = meeting_update.model_dump(exclude_unset=True)
    if not meeting_dict:
         raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="No update data provided")

    updated_meeting = await collection.find_one_and_update(
        {"_id": validated_meeting_oid},
        {"$set": meeting_dict},
        return_document=ReturnDocument.AFTER
    )
    if updated_meeting:
        return MeetingInDB(**updated_meeting)
    raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail=f"Meeting with id {meeting_id} not found for update")

@router.delete("/{meeting_id}", status_code=status.HTTP_204_NO_CONTENT)
async def delete_meeting(
    meeting_id: str = Path(..., description="The BSON ObjectId of the meeting (meeting_id) as a string"),
    collection = Depends(get_meeting_collection)
):
    """Deletes a meeting."""
    validated_meeting_oid = validate_object_id_sync(meeting_id)
    delete_result = await collection.delete_one({"_id": validated_meeting_oid})
    if delete_result.deleted_count == 0:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail=f"Meeting with id {meeting_id} not found for deletion")
    return
